compressionLevel: mixed

enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  "@backstage/repo-tools@*":
    dependencies:
      "@microsoft/api-extractor-model": "*"
      "@microsoft/tsdoc": "*"
      "@microsoft/tsdoc-config": "*"
  "@spotify/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/parser": "*"
  "@storybook/addon-links@*":
    dependencies:
      react: "*"
  "@storybook/react-vite@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "root@workspace:.":
    dependencies:
      react: "*"
      react-dom: "*"
  "@material-ui/icons@*":
    dependencies:
      "@material-ui/core": "*"
  "app-next-example-plugin@*":
    dependencies:
      "@material-ui/core": "*"
  "yarn-plugin-backstage@*":
    dependencies:
      "@yarnpkg/cli": "*"
      "@yarnpkg/plugin-git": "*"
      "@yarnpkg/plugin-pack": "*"
  "@yarnpkg/plugin-essentials@*":
    dependencies:
      "@yarnpkg/cli": "*"
  "@yarnpkg/plugin-git@*":
    dependencies:
      "@yarnpkg/cli": "*"
  "@yarnpkg/plugin-pack@*":
    dependencies:
      "@yarnpkg/cli": "*"

